image: docker:latest

# This file is a template, and might need editing before it works on your project.
push to docker hub:
  # Official docker image.
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:latest" -t "$CI_REGISTRY_IMAGE:0.1.$CI_PIPELINE_ID" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker image rm "$CI_REGISTRY_IMAGE:latest"
    - docker image rm "$CI_REGISTRY_IMAGE:0.1.$CI_PIPELINE_ID"
  only:
    - master

test build:
  # Official docker image.
  image: docker:latest
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:test-0.1.$CI_PIPELINE_ID" .
    - docker image rm "$CI_REGISTRY_IMAGE:test-0.1.$CI_PIPELINE_ID"
  except:
    - master
